apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions-job
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
          - name: django-clearsession-job
            image: django_app:latest
            command: ['python', 'manage.py', 'clearsessions']
            imagePullPolicy: Never
            envFrom:
            - configMapRef:
                name: postgres-config
          restartPolicy: OnFailure